### ISSUE TITLE
Unable to get current user information

### ISSUE THREAD

**Issue by dennis-nguyen** [tokusumi/fastapi-cloudauth#21]
hi, is there any way to pull the cognito id from the payload when the access token is valid?

**Comment by tokusumi** [comment]
Sorry for late response @dennis-nguyen 🙇 🙇 🙇 .

v0.3.0 was released in Pypi, including updates to be able to pull the cognito id from payload in access token. 
Please try it and see readme. 

Ask me again If readme is not helpful for you.

**Comment by dennis-nguyen** [comment]
thank you so much!
