### ISSUE TITLE
auto_error setting not passed to HTTPBearer dependencies

### ISSUE THREAD

**Issue by mjvdvlugt** [tokusumi/fastapi-cloudauth#23]
Hi guys, thanks for writing this implementation! 

I'm currently trying to fit this one into our set-up but I run into an issue with `auto_error=False` setting not being respected by the dependency injections inside fastapi_cloudauth. Fastapi-cloudauth builds on the fastapi `HTTPBearer` dependency injection, which raises an `HTTPException` when the credentials are not found in the headers. To prevent this exception, it supports the `auto_error=False` option. We need this to support other authentication methods.

Our authentication set-up is based on [this medium article](https://medium.com/data-rebels/fastapi-how-to-add-basic-and-cookie-authentication-a45c85ef47d3) to combine multiple types of authentication. To make this work, the "auto_error=False" is essential, to make sure none of the authentication methods block each other. _(see example implementation below)_

**Proposed fix:**
In `base.py`, there are these dependency injections for HTTPBearer(), which currently don't pass the auto_error parameter: https://github.com/tokusumi/fastapi-cloudauth/blob/36d947fd3e638683fa1cb96e194bdaa054d92ee9/fastapi_cloudauth/base.py#L153 and https://github.com/tokusumi/fastapi-cloudauth/blob/36d947fd3e638683fa1cb96e194bdaa054d92ee9/fastapi_cloudauth/base.py#L192

These dependencies do support the `auto_error` parameter, like: `HTTPBearer(auto_error=self.auto_error)`. Possibly you'd want to set this up as a partial function in the constructor.

---
**For reference: example implementation**
_This fails on an HTTPException from HTTPBearer when the OAuth headers are not passed - which unfortunately is the case when another authentication method is used.._
```
api_key_query_dependency = APIKeyQuery(name=settings.api_key_name, auto_error=False)
api_key_header_dependency = APIKeyHeader(name=settings.api_key_name, auto_error=False)
api_key_cookie_dependency = APIKeyCookie(name=settings.api_key_name, auto_error=False)
cognito_auth_dependency = Cognito(region=settings.aws_region,
                                  userPoolId=settings.aws_cognito_user_pool_id,
                                  auto_error=False
                                  ).scope("users")


async def get_authorization(
        api_key_query: str = Security(api_key_query_dependency),
        api_key_header: str = Security(api_key_header_dependency),
        api_key_cookie: str = Security(api_key_cookie_dependency),
        cognito_auth: str = Depends(cognito_auth_dependency),
) -> Security:
    if not cognito_auth \
            or api_key_query == settings.api_key \
            or api_key_header == settings.api_key \
            or api_key_cookie == settings.api_key:
        raise HTTPException(
            status_code=HTTP_403_FORBIDDEN, detail="Could not validate credentials"
        )
```

**Comment by mjvdvlugt** [comment]
I wrote a possible fix for this: https://github.com/tokusumi/fastapi-cloudauth/pull/24

**Comment by tokusumi** [comment]
Really appreciate for your feedback and pull request @mjvdvlugt 👍 
I'd like to release a few days later, because I want to extend this as extract user info from access token, else.

**Comment by tokusumi** [comment]
@mjvdvlugt , v0.3.0 was released in Pypi, including this modification. Please try to update it. 🙇 🙇 🙇

**Comment by mjvdvlugt** [comment]
Thanks!!! It works like a charm!!
