### ISSUE TITLE
Firebase x509 issue

### ISSUE THREAD

**Issue by yu-ichiro** [tokusumi/fastapi-cloudauth#33]
`python-jose` doesn't support x509 certificates without the extra install option (anymore? I not quite sure if it was a silent breaking change).
This breaks the FirebaseCurrentUser's JWKS generation because google gives x509 files for the public key.

the recommended setup on `python-jose` is using `cryptography` as the background, setup as following

```
pip install python-jose[cryptography]
```

but is sort of a debate I guess (acknowledging the fact that cryptography requires building and is not a small dependency)

At least it needs some documentation about it, so I would like to know whats good for this library.

**Comment by yu-ichiro** [comment]
@tokusumi could you take a look at this when you have time? Thank you for your great work on this project🙏

**Comment by tokusumi** [comment]
Thank you @yu-ichiro!
Decided to add `cryptography` by default for simplicity.
If side-effect happened, really appreciate to open new issue.
