### ISSUE TITLE
How to inject auth globally and then use .scope?

### ISSUE THREAD

**Issue by spawn-guy** [tokusumi/fastapi-cloudauth#39]
i have this code

```
async def init_auth(app: FastAPI) -> None:
    logger.info("Auth: Configuring connection to {0}", repr(AUTH0_DOMAIN))
    app.state.auth0_client = Auth0(domain=AUTH0_DOMAIN)
    logger.info("Auth: Connection configured")


def _get_client(request: Request) -> Auth0:
    return request.app.state.auth0_client


def get_auth() -> Callable:
    return _get_client
```

`init_auth` is triggered on ` app.add_event_handler("startup", init_auth(application))`

then this code does work
```
@router.get("/something",
            response_model=Any,
            dependencies=[
                Depends(get_auth)
            ]
            )
async def get_something(
        request: Request
):
return []
```

i would like to use `auth.scope("read:something")` with `Depends` but i can't seem to make it work

```
def get_auth_scoped(
        *,
        scope_name: str,
        client: Auth0 = Depends(get_auth)
) -> Callable:
    return client.scope(scope_name=scope_name)
```
and
```
@router.get("/something",
            response_model=Any,
            dependencies=[
                Depends(get_auth_scoped(scope_name="read:something"))
            ]
            )
async def get_something(
        request: Request
):
return []
```
it results in a `AttributeError: 'Depends' object has no attribute 'scope'`

what am i missing here? please help?

**Comment by spawn-guy** [comment]
we've found a different and an easier way as documentation suggests

**Comment by tokusumi** [comment]
@spawn-guy sorry for late response.
would you mind post your solution for other user?

**Comment by spawn-guy** [comment]
even though we migrated to `fastapi-auth0` (although i wanted to use this one as this one has support for a _few_ jwt issuers) - we've decided to not to instantiate it as a dependency injection, but as a "global" namespaced instance

file: `app/core/auth.py`
```
from fastapi_cloudauth import Auth0
auth0 = Auth0(domain=domain=AUTH0_DOMAIN)
```

then in another route we can use it as
```
from app.core.auth import auth0

@router.get("/something",
            response_model=Any,
            dependencies=[
                Depends(auth0.scope("read:something"))
            ]
            )
async def get_something(
        request: Request
):
    return []
```

**Comment by tivaliy** [comment]
This issue is closed, but I still have a question and faced with exact problem, so how to use Cognito/Auth0.. etc instance as a part of app context. Any thoughts?

**Comment by spawn-guy** [comment]
it's been some time, so i don't recall many things, but

@tivaliy try the snippet above. but replace `Auth0` with `Cognito`.

create an instance in 1 file (`app/core/auth.py`) - import that instance in the router(s)

**Comment by tivaliy** [comment]
@spawn-guy,

Thank you for the response, but the idea in my case is to use exact approach you mentioned in the very beginning of this thread.

**Comment by spawn-guy** [comment]
> @spawn-guy,
> 
> Thank you for the response, but the idea in my case is to use exact approach you mentioned in the very beginning of this thread.

Well, good luck. Let us know when/if you will figure it out
