### ISSUE TITLE
Auth0 token

### ISSUE THREAD

**Issue by guillemfrancisco** [tokusumi/fastapi-cloudauth#4]
First of all, thanks for your work, easy and clear to use 😄 

The issue I'm facing isn't related to repo itself, but on how to generate the Auth0 token to have all the needed information to use the methods properly.

For some endpoints that I'm implementing I'll just need to check if the token has the required scopes and for some others I'll need to use: `current_user: Auth0Claims = Depends(auth.get_current_user)`. However I can't find a way to request to `Auth0` a token with all of this information: `username` and `scopes`. I don't know if I'm misunderstanding some information/concepts or what is going wrong...

Would appreciate some information with the steps to follow. Thanks in advance!

**Comment by tokusumi** [comment]
I couldn't find something to satisfy your needs, sorry. 

you probably add scopes as meta-data in ID token, but it is not probably simple. just sending one of them as parameter or body may be simple solution.

**Comment by guillemfrancisco** [comment]
Thanks @tokusumi for the reply. I have been exploring deeply the issue and there are different approaches but 
the one that suits best our needs is to use an `Auth0 Rule` configured like this:

```
function (user, context, callback) {
  // This rule adds the authenticated user's name to the access token.
  var namespace = 'https://example.com/';

  context.accessToken[namespace + 'username'] = user.name;
  return callback(null, user, context);
}
```

And then simply changing the class `Auth0Claims` class to:

```
Auth0Claims(BaseModel):
    username: str = Field(alias="https://example.com/username")
```

With this simple modification you can have "all" in one 😄
