### ISSUE TITLE
Cannot access `/users/` using the AWS Cognito configuration

### ISSUE THREAD

**Issue by IshakAhmed** [tokusumi/fastapi-cloudauth#53]
Using the authorization modal (in the docs) ...

- if I insert an **`id_token`** and attempt to access the `/users/` endpoint a `JWTClaimsError` is caught (i.e. "No access_token provided to compare against at_hash claim.")
  - See [line 153 in `verifications.py`](https://github.com/tokusumi/fastapi-cloudauth/blob/1a335a42ba89708e31e560b2df14dfb02ea378ea/fastapi_cloudauth/verification.py#L153)
- if I insert an **`access_token`** and attempt to access the `/users/` endpoint the `token_use` claim is flagged (because it is equal to "id").
  - See [line 86 in `cognito.py`](https://github.com/tokusumi/fastapi-cloudauth/blob/1a335a42ba89708e31e560b2df14dfb02ea378ea/fastapi_cloudauth/cognito.py#L86)

What am I missing?

**Comment by ninjix** [comment]
I am running into the same error condition. Any luck on figuring this out?

**Comment by ninjix** [comment]
I got it working for the standard Access Token by modifying the `token_use` parameter of the `CognitoCurrentUser` class to use the `access` value and I changed the `CognitoClaims` class `username` field. 

All the validation exception catching made for some hours of debugging to figure out what was going on. Now `/user/` works from the Swagger docs page when you use the Authorization button with a access_token.

Substituting the module classes with my own to make the docs example work.

```
class MyCognitoClaims(BaseModel):
    username: str = Field(alias="username")
    email: str = Field(None, alias="email")


class MyCognitoCurrentUser(UserInfoAuth):
    """
    Verify ID token and get user info of AWS Cognito
    """

    user_info = MyCognitoClaims

    def __init__(
            self, region: str, userPoolId: str, client_id: str, *args: Any, **kwargs: Any,
    ):
        url = f"https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json"
        jwks = JWKS.fromurl(url)
        super().__init__(
            jwks,
            user_info=self.user_info,
            audience=client_id,
            issuer=f"https://cognito-idp.{region}.amazonaws.com/{userPoolId}",
            extra=CognitoExtraVerifier(
                client_id=client_id,
                issuer=f"https://cognito-idp.{region}.amazonaws.com/{userPoolId}",
                token_use={"access"},
            ),
            *args,
            **kwargs,
        )
```
