### ISSUE TITLE
How can I get the groups/scopes a user is associated in Cognito?

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [tokusumi/fastapi-cloudauth#79]
So I implemented my apis with Cognito and this library and everything works really well but I have a couple requests that I wanted to chose what data to return based on the scope of the user. For example if the user scope  is admin return all entries but if not only return the entries for that user. 

Is this possible with this library?

**Comment by walter-0** [comment]
@DEADSEC-SECURITY Did you ever solve this? If so, what was the solution?
